logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway
server:
  port: 9090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery.locator.enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "X-Requested-With"
              - "Access-Control-Request-Method"
              - "Access-Control-Request-Headers"
              - "Credentials"
            exposed-headers:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Access-Control-Request-Credentials"


      routes:
        - id: season-service
          uri: lb://seasonmatch
          predicates:
            - Path=/season/**,/matchDay/**
        - id: match-service
          uri: lb://match
          predicates:
            - Path=/match/**,/details-match/**
        - id: player-service
          uri: lb://playerteam
          predicates:
            - Path=/player/**,/team/**

  main:
    web-application-type: reactive





